<div class="wrap">
	<div class="icon32" id="icon-options-general"><br></div>
	<h2>AssetsMinify's configuration</h2>
	<p>&nbsp;</p>
	<?php if($this->systemMessage){ ?>
		<div style="display:block !important;" class="updated <?php echo $this->systemMessage[1]."-am"; ?>" id="message"><p><?php echo $this->systemMessage[0]; ?></p></div>
	<?php } ?>
	<form method="post" action="options.php">
		<?php settings_fields('am_options_group'); ?>
		<table class="form-table">
			<tbody>
				<tr valign="top">
					<th scope="row">
						<label for="am_sass_path">Sass compiler's path (required only for .sass format - not .scss)</label>
					</th>
					<td>
						<input name="am_sass_path" type="text" id="am_sass_path" value="<?php echo get_option('am_sass_path', '/usr/bin/sass') ?>" class="regular-text">
					</td>
				</tr>
				<tr valign="top">
					<th scope="row">
						<label for="am_compress_styles">Compress styles</label>
					</th>
					<td>
						<input name="am_compress_styles" type="checkbox" id="am_compress_styles" value="1" <?php checked(1, get_option('am_compress_styles', 1)); ?>>
						<span class="description">Use with care! Some background-images may not be displayed if running a WordPress unusual environment.</span>
					</td>
				</tr>
				<tr valign="top">
					<th scope="row">
						<label for="am_compress_scripts">Compress scripts</label>
					</th>
					<td>
						<input name="am_compress_scripts" type="checkbox" id="am_compress_scripts" value="1" <?php checked(1, get_option('am_compress_scripts', 1)); ?>>
					</td>
				</tr>
				<tr valign="top">
					<th scope="row">
						<label for="am_async_flag_header">Async attribute on header's script tag</label>
					</th>
					<td>
						<input name="am_async_flag_header" type="checkbox" id="am_async_flag_header" value="1" <?php checked(1, get_option('am_async_flag_header', 1)); ?>>
					</td>
				</tr>
				<tr valign="top">
					<th scope="row">
						<label for="am_async_flag_footer">Async attribute on footer's script tag</label>
					</th>
					<td>
						<input name="am_async_flag_footer" type="checkbox" id="am_async_flag_footer" value="1" <?php checked(1, get_option('am_async_flag_footer', 1)); ?>>
					</td>
				</tr>
				<tr valign="top">
					<th scope="row">
						<label for="am_leverage_browser_caching">Leverage browser caching</label>
					</th>
					<td>
						<input name="am_leverage_browser_caching" type="checkbox" id="am_leverage_browser_caching" value="1" <?php checked(1, get_option('am_leverage_browser_caching', 1)); ?>>
					</td>
				</tr>
				<tr valign="top">
					<th scope="row">
						<label for="am_enable_compression">Enable compression</label>
					</th>
					<td>
						<input name="am_enable_compression" type="checkbox" id="am_enable_compression" value="1" <?php checked(1, get_option('am_enable_compression', 1)); ?>>
						<span class="description">Compressing resources with gzip or deflate can reduce the number of bytes sent over the network.</span>
					</td>
				</tr>
				<tr valign="top">
					<th scope="row">
						<label for="am_files_to_exclude">Resources to exclude</label>
					</th>
					<td>
						<textarea name="am_files_to_exclude" id="am_files_to_exclude" cols="60" rows="5"><?php echo get_option('am_files_to_exclude') ?></textarea>
						<div>
							<span class="description">Fill in the filename of the resources you don't want to be managed from AssetsMinify, separated by comma. (eg. custom-carousel.js, slideshow.js)</span>
						</div>
					</td>
				</tr>
				<tr valign="top">
					<th scope="row">
						<label for="am_dev_mode">Development Mode</label>
					</th>
					<td>
						<input name="am_dev_mode" type="checkbox" id="am_dev_mode" value="1" <?php checked(1, get_option('am_dev_mode')); ?>>
						<span class="description">If active, the cache will be flushed on every reload. DON'T USE THIS IN PRODUCTION!</span>
					</td>
				</tr>
			</tbody>
		</table>
		<p class="submit">
			<input type="submit" name="submit" id="submit" class="button button-primary" value="Save" style="margin-right:10px"> <a href="<?php echo admin_url( "options-general.php?page=assets-minify&empty_cache" ) ?>">Empty AssetsMinify's Cache</a>
		</p>
	</form>
</div>
